language: node_js
node_js:
  - '0.6'
  - '0.8'
  - '0.10'
  - '0.12'
  - '1.0'
  - '1.6'

sudo: false

before_script:
- "mysql -e 'create database node_mysql;'"

script:
  - "test $TRAVIS_NODE_VERSION != '0.6' || npm test"
  - "test $TRAVIS_NODE_VERSION  = '0.6' || npm run-script test-ci"

after_script:
  - "test $TRAVIS_NODE_VERSION = '0.6' || npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"

env:
  - MYSQL_HOST=localhost MYSQL_DATABASE=node_mysql MYSQL_USER=root MYSQL_PASSWORD=

mysql:
  adapter: mysql2
  username: root
  encoding: utf8
  database: node_mysql
